<a href="https://colab.research.google.com/github/Pranav210905/Pandas-/blob/main/Pandas_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Run this code cell
import numpy as np
import pandas as pd

In [3]:
# Upload the data to colab before executing this code cell
data = pd.read_csv('/content/drive/MyDrive/CO2_Emissions_Canada2.csv')
data.head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230.0
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232.0
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255.0
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267.0
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212.0


---
---
**1.Write a command to get the descriptive statistics of the dataset. Also, deal with duplicates in the given dataframe**

In [4]:
data.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7383.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7381.000000
mean,3.159813,5.615030,12.556534,9.041706,10.975071,27.481652,250.578377
std,1.354229,1.828307,3.500274,2.224456,2.892506,7.231879,58.512619
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [5]:
# get the number of duplicate rows in the entire dataframe
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7380    False
7381    False
7382    False
7383    False
7384    False
Length: 7385, dtype: bool

In [6]:
# Drop duplicates
data.drop_duplicates()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219.0
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232.0
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240.0
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232.0
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248.0

---
**2.What techniques can be used to fill in missing values for numerical columns? Write code to fill missing values in the "Engine Size (L)" column with the average engine size.**

In [7]:
# write your code here
avg_engine_size=data['Engine Size(L)'].mean()
data['Engine Size(L)'].fillna(avg_engine_size)

0       2.0
1       2.4
2       1.5
3       3.5
4       3.5
       ...
7380    2.0
7381    2.0
7382    2.0
7383    2.0
7384    2.0
Name: Engine Size(L), Length: 7385, dtype: float64

---
---
**3.Determine the total number of vehicles for each fuel type available in the dataset.**

In [10]:
# write your code here
data.groupby('Fuel Type')['Vehicle Class'].count()

Fuel Type
D     175
E     370
N       1
X    3637
Z    3202
Name: Vehicle Class, dtype: int64

---
---
**4.Calculate and display the average CO2 emissions for each vehicle class in ascending order.**

In [12]:
# write your code here
data.groupby('Vehicle Class')['CO2 Emissions(g/km)'].mean().sort_values()

Vehicle Class
STATION WAGON - SMALL       200.067460
COMPACT                     216.670911
MID-SIZE                    222.430212
MINICOMPACT                 236.230769
SUV - SMALL                 236.292523
SPECIAL PURPOSE VEHICLE     237.597403
STATION WAGON - MID-SIZE    238.698113
SUBCOMPACT                  246.502479
MINIVAN                     262.312500
FULL-SIZE                   263.316119
TWO-SEATER                  277.454348
PICKUP TRUCK - SMALL        278.968553
PICKUP TRUCK - STANDARD     301.513011
SUV - STANDARD              304.836735
VAN - CARGO                 361.500000
VAN - PASSENGER             397.212121
Name: CO2 Emissions(g/km), dtype: float64

---
---
**5.Identify which car manufacturers have above-average fuel consumption compared to all manufacturers.**

In [13]:
# write your code here
#calculate the average of all manufacturers
avg_fuel=data['Fuel Consumption Comb (L/100 km)'].mean()
avg_man_fuel=data.groupby('Make')['Fuel Consumption Comb (L/100 km)'].mean()
avg_set=avg_man_fuel[avg_man_fuel>avg_fuel]
avg_set

Make
ASTON MARTIN     14.582979
BENTLEY          15.567391
BUGATTI          22.200000
CADILLAC         11.493038
CHEVROLET        11.973980
CHRYSLER         11.790909
DODGE            12.510163
FORD             12.002548
GENESIS          12.088000
GMC              13.955793
JAGUAR           11.651250
LAMBORGHINI      17.256098
LAND ROVER       12.771765
LINCOLN          11.512500
MASERATI         13.619672
MERCEDES-BENZ    11.917184
PORSCHE          11.106649
RAM              13.022680
ROLLS-ROYCE      16.690000
SRT              16.900000
Name: Fuel Consumption Comb (L/100 km), dtype: float64


---
**6.Investigate which combination of vehicle class and transmission type yields the best fuel efficiency (lowest combined fuel consumption).**

In [14]:
# Get the average fuel consumption for each vehicle class and Fuel Type combination
best=data.groupby(['Vehicle Class','Fuel Type'])['Fuel Consumption Comb (L/100 km)'].mean()
best

Vehicle Class             Fuel Type
COMPACT                   D             6.800000
                          E            11.106250
                          X             7.957813
                          Z            10.561308
FULL-SIZE                 D             8.533333
                          E            15.124000
                          X            10.029078
                          Z            12.578618
MID-SIZE                  D             7.469231
                          E            14.286957
                          N            12.700000
                          X             8.237856
                          Z            11.180864
MINICOMPACT               X             7.834091
                          Z            10.532979
MINIVAN                   E            16.509091
                          X            11.205797
PICKUP TRUCK - SMALL      D            10.391667
                          X            11.953333
PICKUP TRUCK - STANDARD   D            10.080000
                          E            17.569369
                          X            13.105249
                          Z            14.026667
SPECIAL PURPOSE VEHICLE   E            13.772727
                          X            10.189474
                          Z            10.722222
STATION WAGON - MID-SIZE  X             8.850000
                          Z            11.375862
STATION WAGON - SMALL     D             6.922222
                          X             8.292265
                          Z             9.509677
SUBCOMPACT                D             6.500000
                          X             9.651799
                          Z            10.858369
SUV - SMALL               D             8.095455
                          E            14.218182
                          X            10.030590
                          Z            10.598099
SUV - STANDARD            D            10.028125
                          E            18.182558
                          X            12.637267
                          Z            13.827458
TWO-SEATER                X             7.878947
                          Z            12.095465
VAN - CARGO               E            21.740000
                          X            16.200000
VAN - PASSENGER           E            23.294737
                          X            17.534043
Name: Fuel Consumption Comb (L/100 km), dtype: float64

In [15]:
# get only the first row in the aggregated output
best.head(1)

Vehicle Class  Fuel Type
COMPACT        D            6.8
Name: Fuel Consumption Comb (L/100 km), dtype: float64

---
---
**7.Determine which combination of engine size and fuel type results in the highest average CO2 emissions.**

In [16]:
# Group the data by 'Engine size' and 'Fuel Type', then calculate the mean of 'CO2 Emissions(g/km)' for each group.
# Sort the resulting mean values in descending order to show which combinations of engine size and fuel types have the highest average CO2 emissions.
dataVal=data.groupby(['Engine Size(L)','Fuel Type'])['CO2 Emissions(g/km)'].mean().sort_values(ascending=False)
dataVal.head(1)

Engine Size(L)  Fuel Type
8.0             Z            522.0
Name: CO2 Emissions(g/km), dtype: float64

---
---
**8. Filter the dataset to find all mid-size cars that have fuel consumption greater than 12 L/100 km and CO2 emissions exceeding 200 g/km.**

In [19]:
# write your code here
data[data['Vehicle Class']=='MID-SIZE'][data['Fuel Consumption Comb (L/100 km)']>12][data['CO2 Emissions(g/km)']>200]

<ipython-input-19-23cffce66879>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Vehicle Class']=='MID-SIZE'][data['Fuel Consumption Comb (L/100 km)']>12][data['CO2 Emissions(g/km)']>200]
<ipython-input-19-23cffce66879>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Vehicle Class']=='MID-SIZE'][data['Fuel Consumption Comb (L/100 km)']>12][data['CO2 Emissions(g/km)']>200]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
55,AUDI,RS 7,MID-SIZE,4.0,8,AS8,Z,15.5,8.8,12.5,23,293.0
61,AUDI,S6,MID-SIZE,4.0,8,A7,Z,14.2,9.7,12.2,23,281.0
62,AUDI,S7,MID-SIZE,4.0,8,A7,Z,14.2,9.7,12.2,23,281.0
63,AUDI,S8,MID-SIZE,4.0,8,AS8,Z,15.8,9.2,12.8,22,300.0
74,BENTLEY,FLYING SPUR,MID-SIZE,6.0,12,AS8,Z,20.3,11.9,16.5,17,388.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7123,MASERATI,Ghibli,MID-SIZE,3.0,6,AS8,Z,14.1,9.8,12.2,23,286.0
7124,MASERATI,Ghibli S,MID-SIZE,3.0,6,AS8,Z,14.1,9.8,12.2,23,286.0
7125,MASERATI,Ghibli S Q4,MID-SIZE,3.0,6,AS8,Z,14.7,9.9,12.6,22,295.0
7173,MERCEDES-BENZ,AMG E 63 S 4MATIC+,MID-SIZE,4.0,8,A9,Z,16.0,10.5,13.5,21,318.0
7292,ROLLS-ROYCE,Wraith,MID-SIZE,6.6,12,AS8,Z,19.6,12.8,16.5,17,387.0

---
---
**9.Find the range (maximum - minimum) of CO2 emissions for compact SUVs in the dataset.**

In [24]:
# write your code here
require_data=data[data['Vehicle Class']=='SUV - SMALL']
max=require_data['CO2 Emissions(g/km)'].max()
min=require_data['CO2 Emissions(g/km)'].min()
max,min
range=max-min
range

225.0

---
---
**10.Analyze whether there is a correlation between fuel consumption (combined) and CO2 emissions.**

In [25]:
# write your code here
correlation=data[['Fuel Consumption Comb (L/100 km)','CO2 Emissions(g/km)']].corr()

In [26]:
# Print the specific correlation coefficient between the two columns.
correlation

,Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
Fuel Consumption Comb (L/100 km),1.000000,0.918017
CO2 Emissions(g/km),0.918017,1.000000

# End!