<a href="https://colab.research.google.com/github/Pranav210905/Pandas-/blob/main/Pandas_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Run this code cell
import numpy as np
import pandas as pd

In [4]:
# Upload the data to colab before executing this code cell
data = pd.read_csv('/content/drive/MyDrive/CO2_Emissions_Canada2.csv')
data.head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230.0
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232.0
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255.0
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267.0
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212.0

---
---
**1.Check and deal with duplicates in the given dataframe**

In [5]:
# get the number of duplicate rows in the entire dataframe
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7380    False
7381    False
7382    False
7383    False
7384    False
Length: 7385, dtype: bool

In [7]:
# Drop duplicates
data.drop_duplicates(inplace=True)

---
**2.Check for missing values and deal with them using suitable technique**

In [8]:
# write your code here
data.isnull()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,False,False,False,False,False,False,False,False,False,False,False,False
7381,False,False,False,False,False,False,False,False,False,False,False,False
7382,False,False,False,False,False,False,False,False,False,False,False,False
7383,False,False,False,False,False,False,False,False,False,False,False,False
7384,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6283 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              6283 non-null   object
 1   Model                             6283 non-null   object
 2   Vehicle Class                     6283 non-null   object
 3   Engine Size(L)                    6281 non-null   float64
 4   Cylinders                         6283 non-null   int64
 5   Transmission                      6283 non-null   object
 6   Fuel Type                         6283 non-null   object
 7   Fuel Consumption City (L/100 km)  6283 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   6283 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  6283 non-null   float64
 10  Fuel Consumption Comb (mpg)       6283 non-null   int64
 11  CO2 Emissions(g/km)               6279 non-null   float64
dtypes: float64(5), int64(2), object(5)
memory usage: 638.1+ KB

In [9]:
data.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      2
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 4
dtype: int64

---
---
**3.Find the number of vehicles present in each `vehicle class`**

In [15]:
data.groupby(by="Vehicle Class").count()

,Make,Model,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
Vehicle Class,,,,,,,,,,,
COMPACT,903,903,902,903,903,903,903,903,903,903,902
FULL-SIZE,508,508,508,508,508,508,508,508,508,508,508
MID-SIZE,984,984,984,984,984,984,984,984,984,984,983
MINICOMPACT,275,275,275,275,275,275,275,275,275,275,274
MINIVAN,61,61,61,61,61,61,61,61,61,61,61
PICKUP TRUCK - SMALL,133,133,133,133,133,133,133,133,133,133,133
PICKUP TRUCK - STANDARD,475,475,475,475,475,475,475,475,475,475,475
SPECIAL PURPOSE VEHICLE,65,65,65,65,65,65,65,65,65,65,65
STATION WAGON - MID-SIZE,45,45,45,45,45,45,45,45,45,45,45
STATION WAGON - SMALL,214,214,214,214,214,214,214,214,214,214,214
SUBCOMPACT,533,533,533,533,533,533,533,533,533,533,532
SUV - SMALL,1005,1005,1005,1005,1005,1005,1005,1005,1005,1005,1005
SUV - STANDARD,613,613,613,613,613,613,613,613,613,613,613
TWO-SEATER,381,381,380,381,381,381,381,381,381,381,381
VAN - CARGO,22,22,22,22,22,22,22,22,22,22,22
VAN - PASSENGER,66,66,66,66,66,66,66,66,66,66,66

---
---
**4.Calculate the average fuel consumption of each vehicle class and print in descending order**

In [18]:
# write your code here
data.groupby(by="Vehicle Class")['Fuel Consumption Comb (L/100 km)'].mean().sort_values(ascending=False)

Vehicle Class
VAN - PASSENGER             19.192424
VAN - CARGO                 18.718182
PICKUP TRUCK - STANDARD     13.941053
SUV - STANDARD              13.783524
TWO-SEATER                  12.121522
MINIVAN                     11.854098
FULL-SIZE                   11.669488
PICKUP TRUCK - SMALL        11.639098
SPECIAL PURPOSE VEHICLE     10.775385
SUBCOMPACT                  10.494934
STATION WAGON - MID-SIZE    10.326667
SUV - SMALL                 10.252537
MINICOMPACT                 10.194909
MID-SIZE                     9.617581
COMPACT                      9.393355
STATION WAGON - SMALL        8.656542
Name: Fuel Consumption Comb (L/100 km), dtype: float64

---
---
**5.Which car manufacturers are having average co2 emissions above the average of all manufacturers?**

In [30]:
# write your code here
#calculate the average of all manufacturers
#get the manufacturers having average co2 emissions above the average of all manufacturers
avg_Co2=data['CO2 Emissions(g/km)'].mean()
avg_Co2
avg_co2_manfactures=data.groupby('Make')['CO2 Emissions(g/km)'].mean()
avg_set=avg_co2_manfactures[avg_co2_manfactures>avg_Co2].sort_values(ascending=True)
avg_set

Make
BMW              252.514970
AUDI             252.824427
INFINITI         254.011494
PORSCHE          259.192568
FORD             261.285962
CHEVROLET        264.477670
LINCOLN          265.814815
CADILLAC         266.141844
JAGUAR           273.084746
DODGE            277.088889
MERCEDES-BENZ    278.717808
GENESIS          282.571429
LAND ROVER       288.078947
RAM              294.180556
GMC              300.529412
MASERATI         318.134615
ASTON MARTIN     344.282051
BENTLEY          367.914286
ROLLS-ROYCE      388.750000
SRT              389.000000
LAMBORGHINI      402.270270
BUGATTI          522.000000
Name: CO2 Emissions(g/km), dtype: float64


---
**6.Find out which combination of vehicle class and fuel type offers best fuel efficiency.**

In [39]:
# Get the average fuel consumption for each vehicle class and Fuel Type combination
fuels_set=data.groupby(by=['Vehicle Class','Fuel Type'])['Fuel Consumption Comb (L/100 km)'].mean().sort_values()
fuels_set

Vehicle Class             Fuel Type
SUBCOMPACT                D             6.500000
COMPACT                   D             6.790476
STATION WAGON - SMALL     D             6.922222
MID-SIZE                  D             7.435000
TWO-SEATER                X             7.863636
MINICOMPACT               X             7.878378
COMPACT                   X             8.033592
SUV - SMALL               D             8.050000
MID-SIZE                  X             8.225977
STATION WAGON - SMALL     X             8.429932
FULL-SIZE                 D             8.600000
STATION WAGON - MID-SIZE  X             8.727778
STATION WAGON - SMALL     Z             9.500000
SUBCOMPACT                X             9.711200
SUV - STANDARD            D            10.004348
FULL-SIZE                 X            10.038889
SUV - SMALL               X            10.055782
PICKUP TRUCK - STANDARD   D            10.077419
SPECIAL PURPOSE VEHICLE   X            10.159574
PICKUP TRUCK - SMALL      D            10.270000
COMPACT                   Z            10.548852
MINICOMPACT               Z            10.555042
SUV - SMALL               Z            10.580455
SPECIAL PURPOSE VEHICLE   Z            10.722222
SUBCOMPACT                Z            10.745455
COMPACT                   E            11.106250
MID-SIZE                  Z            11.142424
MINIVAN                   X            11.149057
STATION WAGON - MID-SIZE  Z            11.392593
PICKUP TRUCK - SMALL      X            11.881416
TWO-SEATER                Z            12.248108
FULL-SIZE                 Z            12.576190
SUV - STANDARD            X            12.660305
MID-SIZE                  N            12.700000
PICKUP TRUCK - STANDARD   X            13.125949
SUV - STANDARD            Z            13.953360
SPECIAL PURPOSE VEHICLE   E            14.044444
PICKUP TRUCK - STANDARD   Z            14.056000
MID-SIZE                  E            14.113636
SUV - SMALL               E            14.136667
FULL-SIZE                 E            15.086842
VAN - CARGO               X            16.200000
MINIVAN                   E            16.525000
VAN - PASSENGER           X            17.534043
PICKUP TRUCK - STANDARD   E            17.576699
SUV - STANDARD            E            18.293333
VAN - CARGO               E            21.740000
VAN - PASSENGER           E            23.294737
Name: Fuel Consumption Comb (L/100 km), dtype: float64

In [37]:
# get only the first row in the aggregated output
fuels_set.head(1)

Vehicle Class  Fuel Type
SUBCOMPACT     D            6.5
Name: Fuel Consumption Comb (L/100 km), dtype: float64

---
---
**7.Find out which combination of number of cylinders and fuel type has highest carbon emissions.**

In [45]:
# Group the data by 'Cylinders' and 'Fuel Type', then calculate the mean of 'CO2 Emissions(g/km)' for each group.
# Sort the resulting mean values in descending order to show which combinations of cylinders and fuel types
setVal=data.groupby(['Cylinders','Fuel Type'])['CO2 Emissions(g/km)'].mean().sort_values(ascending=False)

In [46]:
# have the highest average CO2 emissions.
setVal.head(1)

Cylinders  Fuel Type
16         Z            522.0
Name: CO2 Emissions(g/km), dtype: float64

---
---
**8.Extract all the small SUVs having fuel comsumption above 15 and co2 emissions above 220.**

In [54]:
# write your code here
data[data['Vehicle Class']=="SUV - SMALL"][data['Fuel Consumption Comb (L/100 km)']>15][data['CO2 Emissions(g/km)']>220]

<ipython-input-54-65c7fa41e16e>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Vehicle Class']=="SUV - SMALL"][data['Fuel Consumption Comb (L/100 km)']>15][data['CO2 Emissions(g/km)']>220]
<ipython-input-54-65c7fa41e16e>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Vehicle Class']=="SUV - SMALL"][data['Fuel Consumption Comb (L/100 km)']>15][data['CO2 Emissions(g/km)']>220]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
206,CHEVROLET,EQUINOX,SUV - SMALL,3.6,6,A6,E,18.8,13.1,16.2,17,259.0
209,CHEVROLET,EQUINOX AWD,SUV - SMALL,3.6,6,A6,E,19.8,13.6,17.0,17,272.0
331,DODGE,JOURNEY FFV,SUV - SMALL,3.6,6,A6,E,18.9,12.9,16.2,17,259.0
465,GMC,TERRAIN,SUV - SMALL,3.6,6,A6,E,18.8,13.1,16.2,17,259.0
468,GMC,TERRAIN AWD,SUV - SMALL,3.6,6,A6,E,19.8,13.6,17.0,17,272.0
2542,DODGE,JOURNEY FFV,SUV - SMALL,3.6,6,A6,E,18.9,12.9,16.2,17,270.0
3614,DODGE,JOURNEY FFV,SUV - SMALL,3.6,6,A6,E,19.1,13.2,16.4,17,274.0
5728,DODGE,Journey FFV,SUV - SMALL,3.6,6,A6,E,19.1,13.2,16.4,17,274.0

---
---
**9.Calculate the interquartile range for co2 emissions by small suvs.**
1. Step 1 : Filter the data for vehicle class small suv
2. step 2 : Calculate quantile 1 for co2 emission
3. step 3 : Calculare quantile 3 for co2 emmision
4. step 4 : calculate the IQR using step 2 and step 4.

In [59]:
# write your code here
suv_data=data[data['Vehicle Class']=="SUV - SMALL"]
q1=suv_data['CO2 Emissions(g/km)'].quantile(0.25)
q3=suv_data['CO2 Emissions(g/km)'].quantile(0.75)
q5=q3-q1
q5

44.0

---
---
**10.Verify whether high fuel comsumption is a contributing factor towards high carbon emissions.**

In [60]:
# write your code here
cor_value=data[['Fuel Consumption Comb (L/100 km)','CO2 Emissions(g/km)']].corr()

In [61]:
# Print the specific correlation coefficient between the two columns.
cor_value

,Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
Fuel Consumption Comb (L/100 km),1.000000,0.916826
CO2 Emissions(g/km),0.916826,1.000000

# End!